# permissions for end users to edit podrepicas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: podrepica-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: podreplicationcontroller
    app.kubernetes.io/part-of: podreplicationcontroller
    app.kubernetes.io/managed-by: kustomize
  name: podrepica-editor-role
rules:
- apiGroups:
  - podreplica-app.my.customecontroller
  resources:
  - podrepicas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - podreplica-app.my.customecontroller
  resources:
  - podrepicas/status
  verbs:
  - get
