---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - podreplica-app.my.customecontroller
  resources:
  - podrepicas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - podreplica-app.my.customecontroller
  resources:
  - podrepicas/finalizers
  verbs:
  - update
- apiGroups:
  - podreplica-app.my.customecontroller
  resources:
  - podrepicas/status
  verbs:
  - get
  - patch
  - update
